sudo: 'true'

env:
  - ARCH=arm

services:
  - 'docker'

script:
  - 'make build'

# after_success:
#   - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
#       docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
#       make push ;
#     fi

notifications:
  email: true
