version: '2.1'

services:
  plex-server:
    container_name: plex-server
    image: plex-media-server:1.13.8.5395-10d48da0d
    network_mode: "host"
    restart: always
    volumes:
      - /config:/config
      - /mnt/data:/media
